// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4QuNCoHhyzvhCRbS4PNvyii0pTqj-6jw',
    appId: '1:124790475640:web:15fe1d40c3dd396a3a568d',
    messagingSenderId: '124790475640',
    projectId: 'cloud-lab1-48aaf',
    authDomain: 'cloud-lab1-48aaf.firebaseapp.com',
    storageBucket: 'cloud-lab1-48aaf.appspot.com',
    measurementId: 'G-EJ92DNL73Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDFD5-nbe8qQhjtmR6QPA1K5cJmui6HIs',
    appId: '1:124790475640:android:b0cb41b94c39baa73a568d',
    messagingSenderId: '124790475640',
    projectId: 'cloud-lab1-48aaf',
    storageBucket: 'cloud-lab1-48aaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1A3glXVKG9KU4bUmC5wFn_ML6uPBcAq8',
    appId: '1:124790475640:ios:51523f6c8210e76a3a568d',
    messagingSenderId: '124790475640',
    projectId: 'cloud-lab1-48aaf',
    storageBucket: 'cloud-lab1-48aaf.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1A3glXVKG9KU4bUmC5wFn_ML6uPBcAq8',
    appId: '1:124790475640:ios:08fc38a0a97339b83a568d',
    messagingSenderId: '124790475640',
    projectId: 'cloud-lab1-48aaf',
    storageBucket: 'cloud-lab1-48aaf.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
